sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: node_js

node_js:
  - stable

install:
  - npm install

script:
  - npm run dist
  - npm test

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

deploy:
  - provider: script
    script: sh .travis/release.sh
    skip_cleanup: true
    on:
      branch: release
  - provider: releases
    api_key: $GITHUB_API_KEY
    file: "dist/angular-hot-livereload.js"
    skip_cleanup: true
    on:
      tags: true
